#' global_LOD
#'
#' Find a global Limit Of Detection (LOD), in terms of a log2 fold change, for positive calls produced on data generated by `seqgendiff`.
#'
#' @param bthin_out The output from `seqgendiff`.
#' @param type One of `mageck` or `drugz`.
#' @param ... A set of data
#'
#' @return A numeric value (a log2 fold change).
global_LOD <- function(bthin_out, type, ...){
  if(class(bthin_out) != "ThinData") stop("'bthin_out' should be an object of class 'ThinData'")
  if(!type %in% c("mageck","drugz")) stop("'type' should be one of 'mageck' or 'drugz'")
  data_list <- list(...)

}
